server {
  listen 80;
  
  # Serve os arquivos estáticos do React
  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  # Proxy para o backend
  # Todas as chamadas para /api/... serão repassadas para o serviço 'backend'
  location /api/ {
    # 'backend' é o nome do serviço Java no docker-compose
    # '/flop/' é o context-path da api Spring
    proxy_pass http://backend:8080/flop/;
  }
}